## Numpy array operations

In [2]:
import numpy as np


In [10]:
arr = np.array([1,2,3,4,5,4,6,7,8,9])
print("Basic " ,arr[2:7])
print("With step",arr[1:8:2])
print("negative indexing ",arr[-3])

Basic  [3 4 5 4 6]
With step [2 4 4 7]
negative indexing  7


In [9]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element : ",arr_2d[1,2])
print("Entire row : ",arr_2d[1])
print("Entire cols : ",arr_2d[:,1])


Specific element :  6
Entire row :  [4 5 6]
Entire cols :  [2 5 8]


## Sorting

In [13]:
unsorted = np.array([3,2,1,4,6,7,6])
print("Sorted array : ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[4,3],[9,6]])
print("\n",arr_2d_unsorted)
print("Sorted 2d array by colums : \n ",np.sort(arr_2d_unsorted,axis=1))

Sorted array :  [1 2 3 4 6 6 7]

 [[3 1]
 [4 3]
 [9 6]]
Sorted 2d array by colums : 
  [[1 3]
 [3 4]
 [6 9]]


## Filtering

In [15]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_no = numbers[numbers%2 == 0]
print("Even : ",even_no)

Even :  [ 2  4  6  8 10]


## Filter with mask

In [17]:
mask = numbers > 5
print("Numbers greater than 5 : ",numbers[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [19]:
indices = [0,3,5,6]
print(numbers[indices])


where_result = np.where(numbers > 1)
print("Np where ",numbers[where_result])

[1 4 6 7]
Np where  [ 2  3  4  5  6  7  8  9 10]


In [21]:
condition_arr = np.where(numbers>3,numbers*2,numbers )
print(condition_arr)

[ 1  2  3  8 10 12 14 16 18 20]


### Adding and removing data

In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concat((arr1,arr2))
print(combined)


[1 2 3 4 5 6]


### Array compactibitty

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compactibilty : ",a.shape == b.shape)

Compactibilty :  True


In [8]:
import numpy as np
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])


with_new_row = np.vstack((original,new_row))
print("Original : \n",original)
print("with new row : \n",with_new_row)


new_colum = np.array([[7],[8]])
with_new_column = np.hstack((original,new_colum))
print("with column : \n",with_new_column)



Original : 
 [[1 2]
 [3 4]]
with new row : 
 [[1 2]
 [3 4]
 [5 6]]
with column : 
 [[1 2 7]
 [3 4 8]]


In [9]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("array after Deleted : ",deleted)

array after Deleted :  [1 2 4 5]
