## Numpy array and basics 
### Learning numpy


In [2]:
import numpy as np

## Creating array list 


In [4]:
arr_1d = np.array([1,2,3,4,5,6])
print("1D array : ",arr_1d)

arr_2d = np.array([[1,2,3,4],[1,2,3,4]])
print("2D array : ",arr_2d)

1D array :  [1 2 3 4 5 6]
2D array :  [[1 2 3 4]
 [1 2 3 4]]


## List vs numpy array 

In [7]:
py_list = [1,2,3,4]
print("Python list multiplication",py_list * 2)

np_array = np.array([1,2,3,4]) # element wise multiplication
print("Python array multiplication",np_array *2 )


import time 
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n operation time : ",time.time() - start)

start = time.time()
np_array = np.arange(100000)*2
print("\n operation time : ",time.time() - start)



Python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
Python array multiplication [2 4 6 8]

 operation time :  0.005417585372924805

 operation time :  0.0009920597076416016


## Creating array  from scratch


In [13]:
zeros = np.zeros((3,4))
print("Zero array : ",zeros)

ones = np.ones((3,3))
print("ones array : ",ones)

full = np.full((2,2)  ,4)
print("Full : ",full)

random = np.random.random((2,3))
print("Random : ",random)

sequence = np.arange(0,12,2)
print("sequence : ",sequence)

Zero array :  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array :  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full :  [[4 4]
 [4 4]]
Random :  [[0.78061773 0.86911522 0.56434107]
 [0.13536036 0.42291763 0.44722807]]
sequence :  [ 0  2  4  6  8 10]


## Vectors , matrix ,tensor

In [16]:
vector = np.array([1,2,3,4])
print("Vector : ",vector)

matrix = np.array([[1,2,3,4],[1,3,4,5]])
print("Matrix : ",matrix)

tensor = np.array([[[1,2],[5,6]],
                    [[5,6],[7,8]]])
print("Tensor : ",tensor)

Vector :  [1 2 3 4]
Matrix :  [[1 2 3 4]
 [1 3 4 5]]
Tensor :  [[[1 2]
  [5 6]]

 [[5 6]
  [7 8]]]


## Array properties 

In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape : ",arr.shape)
print("dimesnion : ",arr.ndim)
print("Size : ",arr.size)
print("Datatype : ",arr.dtype)

Shape :  (2, 3)
dimesnion :  2
Size :  6
Datatype :  int64


## Array reshaping

In [27]:
array = np.arange(12)
print("Original array : ",array)

reshaped_array = array.reshape((3,4))
print("Reshaped array : ",reshaped_array)

flatten = reshaped_array.flatten()
print("Flatten : ",flatten)

revaled = reshaped_array.ravel()
print("Raveled : ",revaled)

transpose = reshaped_array.T
print("Transpose : ",transpose)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
